version: '2.3'

services:
  gotty-docker:
    container_name: gotty
    image: byreqz/gotty:latest
    restart: unless-stopped
    ports:
     - 1234:1234
    environment:
     - port=1234
     - userpass=user:pass
     - title=1234
     - pkgs=htop
     - command=htop
     - use_tmux=true
